BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXX XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XX
		XXXXXXX XX XX XXXXXXXXX XXXXX XXXXXXX
	XXXXX

    XXXX
    XXXXXXXXXXXXXXXXXXX
    XXXX
        BBB BBBBBBBBB BB BBBBBBBBBBB
            XXXXXXXXX
        BBBBBB
    XXXXX
BBBBBBBB