# base image
FROM python:3.6.5-alpine

# set env
ENV PYTHONUNBUFFERED 1

# set working directory
RUN mkdir /code
WORKDIR /code

# add and install requirements
ADD requirements.txt /code/

# install dependencies
RUN apk add --no-cache postgresql-libs && \
  apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

RUN pip install -r requirements.txt --no-cache-dir
RUN apk --purge del .build-deps

# add entrypoint.sh
COPY ./entrypoint-dev.sh /code/entrypoint-dev.sh
RUN chmod +x /code/entrypoint-dev.sh

# add app
ADD . /code/

# run server
CMD ["/code/entrypoint-dev.sh"]




