# Generated by Django 2.1.3 on 2018-12-05 06:19

from django.db import migrations, models
import book.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20181205_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='filepath',
            field=models.FileField(null=True, upload_to=book.models.file_dir_path),
        ),
    ]
