# Generated by Django 2.1.3 on 2018-12-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='books', verbose_name='封面'),
        ),
    ]
