# Generated by Django 2.1.3 on 2018-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='abstract',
            field=models.CharField(max_length=300, null=True, verbose_name='摘要'),
        ),
    ]
